overlay_title: Cubase_Nuendo

# Tracks buttons
rec: REC
mute: MUTE
solo: SOLO
sel: SEL

# Timecode zone
smpte: SMPTE
beats: BEATS
rude_solo: RUDE SOLO

# VPOT Assignment
vpot_assignment: VPOT Assign
track: Up
send: Down
pan: Pan
plugin: 
eq:  EQ
instruments: Fx/Aux

# Fader Banks
fader_banks: Fader Banks
bank_left: < BK
bank_right: BK >
channel_left: < CH
channel_right: CH >
flip: Flip
global_view: Edit

# Display
timecode: Timecode
display: Display
name_value1: Name
name_value2: Value
smpte_beats1: SMPTE
smpte_beats2: BEATS

# Functions
function_select: Function Select
f1: F1
f2: F2
f3: F3
f4: F4
f5: F5
f6: F6
f7: F7
f8: F8

# Global View
global_view_header: Fader Banks
midi_tracks: '1'
inputs: '2'
audio_tracks: '3'
audio_instrument: '4'
aux: '5'
busses: '6'
outputs: '7'
user: '8'

# Modifiers
modifiers: ''
shift: Undo
option: Redo
control: Save
alt: Revert

# Automation
automation: ''
read_off: Read
write: Write
trim: Sends
touch: Project
latch: Mixer
group: Motors

# Utilities
utilities: ''
save: Instr
undo: Master
cancel: Solo D
enter: Shift

# Transport
transport: Transport & Markers
markers: Left
nudge: Right
cycle: Cycle
drop: Punch
replace: Prev
click: Add
tr_solo: Next

rewind: '<<'
forward: '>>'
stop: ◼
play: ▶
record: ●

up: ▲
down: ▼
left: ◀
right: ▶
zoom: Zoom

scrub: Scrub